[menu]
beats_enable = false

[general]
refresh_rate = 120
l2d_size = [ 400.0, 400.0,]

[l2d]
l2d_model = "./model/Lulu_body"
auto_breath = "True"
auto_blink = "True"
tracking_sensitivity = 2
standby_active_rate = 0.5

[llm]
api_key = ""
target_platform = "siliconflow"
target_model = "deepseek-ai/DeepSeek-V3"
