[menu]
beats_enable = false

[general]
refresh_rate = 120
l2d_size = [ 200.0, 600.0,]

[l2d]
l2d_model = "./model/hiyori_free_t08"
auto_breath = "True"
auto_blink = "True"
tracking_sensitivity = 2
standby_active_rate = 0.5
[[l2d.click_action]]
name = "hiyori_m05"
group = "Idle"
index = 2

[[l2d.click_action]]
name = "hiyori_m06"
group = "Tap"
index = 0

[[l2d.standby_action]]
name = "hiyori_m01"
group = "Idle"
index = 0

[[l2d.standby_action]]
name = "hiyori_m02"
group = "Idle"
index = 1

[[l2d.standby_action]]
name = "hiyori_m03"
group = "Flick"
index = 0

[[l2d.standby_action]]
name = "hiyori_m04"
group = "FlickDown"
index = 0

[llm]
api_key = ""
target_platform = "siliconflow"
target_model = "deepseek-ai/DeepSeek-V3"
